# Generated by Django 5.1.1 on 2024-12-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(default='', max_length=255, verbose_name='景区名')),
                ('level', models.CharField(default='', max_length=255, verbose_name='等级')),
                ('discount', models.CharField(default='', max_length=255, verbose_name='折扣')),
                ('province', models.CharField(default='', max_length=255, verbose_name='省份')),
                ('star', models.CharField(default='', max_length=255, verbose_name='热度')),
                ('saleCount', models.CharField(default='', max_length=255, verbose_name='销量')),
                ('detailAddress', models.CharField(default='', max_length=2550, verbose_name='景点详情地址')),
                ('shortInfo', models.CharField(default='', max_length=255, verbose_name='短评')),
                ('detailUrl', models.TextField(default='', verbose_name='详情地址')),
                ('score', models.CharField(default='', max_length=255, verbose_name='评分')),
                ('price', models.CharField(default='', max_length=255, verbose_name='价格')),
                ('commentsLen', models.CharField(default='', max_length=255, verbose_name='评论个数')),
                ('detailIntro', models.TextField(default='', verbose_name='详情介绍')),
                ('img_list', models.ImageField(default='', max_length=2550, upload_to='', verbose_name='图片列表')),
                ('comments', models.TextField(default='', verbose_name='用户评论')),
                ('cover', models.CharField(default='', max_length=2550, verbose_name='封面')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('email', models.CharField(default='', max_length=255, verbose_name='邮箱')),
                ('sex', models.CharField(default='', max_length=255, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=255, verbose_name='地址')),
                ('avatar', models.ImageField(default='avatar/default.png', upload_to='avatar/', verbose_name='头像')),
                ('textarea', models.CharField(default='', max_length=255, verbose_name='个人简介')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.travelinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False, verbose_name='收藏id')),
                ('favorite_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('travel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_favorites', to='app.travelinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_travel_info',
            field=models.ManyToManyField(blank=True, related_name='favorite_travel_info_set', through='app.UserFavorites', to='app.travelinfo'),
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='favorite_travel_info',
            field=models.ManyToManyField(blank=True, related_name='favorite_travel_info_users', through='app.UserFavorites', to='app.travelinfo'),
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='浏览ID')),
                ('browse_time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('travel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_histories', to='app.travelinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_histories', to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='history_travel_info',
            field=models.ManyToManyField(blank=True, related_name='history_travel_info_users', through='app.UserHistory', to='app.travelinfo'),
        ),
    ]
