# Generated by Django 5.1.1 on 2024-09-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_travelinfo_detailintro"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default="", max_length=255, verbose_name="邮箱"),
        ),
    ]
