# Generated by Django 5.1.1 on 2024-09-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="createTime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
    ]
