# Generated by Django 5.1.1 on 2024-12-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavorites",
            fields=[
                (
                    "favorite_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="收藏id"
                    ),
                ),
                (
                    "favorite_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "travel_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_favorites",
                        to="app.travelinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_favorites",
                        to="app.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="travelinfo",
            name="favorite_travel_info",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_users",
                through="app.UserFavorites",
                to="app.travelinfo",
            ),
        ),
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                (
                    "history_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="浏览ID"
                    ),
                ),
                (
                    "browse_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="浏览时间"),
                ),
                (
                    "travel_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_histories",
                        to="app.travelinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_histories",
                        to="app.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="travelinfo",
            name="history_travel_info",
            field=models.ManyToManyField(
                blank=True,
                related_name="history_users",
                through="app.UserHistory",
                to="app.travelinfo",
            ),
        ),
    ]
