# Generated by Django 5.1.1 on 2024-12-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_userfavorites_travelinfo_favorite_travel_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_travel_info",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_travel_info_set",
                through="app.UserFavorites",
                to="app.travelinfo",
            ),
        ),
        migrations.AlterField(
            model_name="travelinfo",
            name="favorite_travel_info",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_travel_info_users",
                through="app.UserFavorites",
                to="app.travelinfo",
            ),
        ),
        migrations.AlterField(
            model_name="travelinfo",
            name="history_travel_info",
            field=models.ManyToManyField(
                blank=True,
                related_name="history_travel_info_users",
                through="app.UserHistory",
                to="app.travelinfo",
            ),
        ),
    ]
